# Generated by Django 3.2.13 on 2023-09-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didiapp', '0002_auto_20230906_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinopeito',
            name='area_do_treino',
            field=models.CharField(max_length=20),
        ),
    ]
