# Generated by Django 3.2.13 on 2023-09-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didiapp', '0003_alter_treinopeito_area_do_treino'),
    ]

    operations = [
        migrations.CreateModel(
            name='treinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('escala_satifacao', models.CharField(choices=[('C', 'Chato'), ('L', 'Legal'), ('M', 'Muito Legal')], max_length=1)),
                ('dor', models.CharField(choices=[('N', 'Nao Doi'), ('D', 'Doi'), ('M', 'Doi Muito')], max_length=1)),
                ('quantidade_semanal_de_exer', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
            ],
        ),
    ]
